name: documentation

on:
  push:
    branches: [main]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX: kintohub
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
            elif [ -e package-lock.json ]; then
            npm ci
            else
            npm i
            fi
            npm run build
      - name: Deploy to Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build
          cname: kintohub.com
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
